apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

resources:
- deployment.yaml

commonLabels:
  app: spring-boot-template-zone-1

images:
- name: registry.hub.docker.com/sszykula/templates
  newName: registry.hub.docker.com/sszykula/templates
  newTag: spring-boot-template-1.1.0
